modLoader="javafml"
loaderVersion="[45,)"
license="All Rights Reserved"

[[mods]]
modId="bettermissiles"
version="1.2.0"
displayName="Better Missiles"
credits="made by FeuSalamander"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-missiles"
logoFile="logo.png"
authors="FeuSalamander"
description="Add missiles to your minecraft adventures."

[[dependencies.bettermissiles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




